### ISSUE TITLE
Rename Tabs

### ISSUE THREAD

**Issue by Steve-Miller** [sillsdev/cog#53]
Across the top are three tabs: Input, Compare, and Analyze. I'm always clicking on Analyze when I really want Compare.

IMO, the Analyze tab should be renamed. It seems to me to be more "Results" of analysis than Analyze.

If you do rename it to Results, Geographical should probably be moved to the Input tab. In fact, I'm thinking it belongs there, anyway.

**Comment by ddaspit** [comment]
I just want to outline the thinking that went into the current naming of the tabs. Cog is split up into three major tasks: inputting/preparing word lists, comparing word lists, and analyzing the comparison results.

The purpose of the Input tab is to help the user to enter their word list data into Cog and then prepare it for comparison. Word lists are entered either manually or by importing. Word lists are prepared for comparison by setting up the segmentation, syllabification, and stemming.

The purpose of the Compare tab is to perform/configure the comparison process and review the comparison results. The idea for this tab is that the user can review the comparison results for any incorrect decisions and then correct them by tweaking the comparison settings.

The purpose of the Analyze tab is to provide different tools for exploring the relationships between the different varieties based on the comparison results. Cog provides ways of looking at these relationships from different perspectives. This is why the Geographical tool is in this tab. Remember that Cog was not intended to be the authoritative format for survey data, including geographical data. The purpose of the Geographical tool is to reveal geographical relationships between varieties. Similar varieties are displayed using the same color, so that you can see how similar varieties are geographically related. It is just another way of looking at the comparison results. In this sense, I think that it is appropriate for the Geographical tool to be in the Analyze tab.

There is more information on this in the [Cog Tutorial](https://github.com/sillsdev/cog/wiki/Cog-Tutorial). I hope that clarifies why the tabs have the names that they have.

**Comment by Steve-Miller** [comment]
Hmm...I see the tasks. The labels still confuse me. But I'm not an ordinary user, so it might be just be me. Maybe it makes sense to a surveyor.
